# ── Production Profile ────────────────────────────────────────────────────────

spring.application.name=TraceLink
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS}
frontend.url=${FRONTEND_URL}

logging.level.org.springframework.security=WARN
logging.level.org.urlshortner.tracelink=INFO